# Generated by Django 4.2.5 on 2023-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_table',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
