# Generated by Django 4.2.5 on 2023-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_travel_table_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='image')),
                ('na', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
    ]
