# Generated by Django 4.2.5 on 2023-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='travel_table',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
