# Generated by Django 4.2.5 on 2023-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_team_pic_alter_travel_table_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='travel_table',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
